model_list:
  - model_name: eu.amazon.nova-pro-v1:0
    owned_by: bedrock
    litellm_params:
      model: bedrock/eu.amazon.nova-pro-v1:0
  - model_name: eu.anthropic.claude-sonnet-4-20250514-v1:0
    owned_by: bedrock
    litellm_params:
      model: eu.anthropic.claude-sonnet-4-20250514-v1:0


litellm_settings:
  set_verbose: true
  request_timeout: 60
  callbacks: ["prometheus"] # logs llm success + failure logs on datadog

general_settings:
  proxy_batch_write_at: 60 # Batch write spend updates every 60s
  database_connection_pool_limit: 10 # limit the number of database connections to = MAX Number of DB Connections/Number of instances of litellm proxy (Around 10-20 is good number)

  # OPTIONAL Best Practices
  disable_error_logs: True # turn off writing LLM Exceptions to DB
  allow_requests_on_db_unavailable: True # Only USE when running LiteLLM on your VPC. Allow requests to still be processed even if the DB is unavailable. We recommend doing this if you're running LiteLLM on VPC that cannot be accessed from the public internet.
