model_list:
  - model_name: titan-text
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1
      aws_region_name: us-east-1
  - model_name: nova-pro
    litellm_params:
      model: bedrock/us.amazon.nova-pro-v1:0
      aws_region_name: us-east-1

litellm_settings:
  callbacks: ["arize_phoenix"]

guardrails:
  - guardrail_name: "bedrock-content-filter"
    litellm_params:
      guardrail: bedrock
      mode: "during_call"
      guardrailIdentifier: os.environ/GUARDRAIL_ID
      guardrailVersion: os.environ/GUARDRAIL_VERSION

router_settings:
  routing_strategy: "cost-based-routing"
  num_retries: 3
  timeout: 60

general_settings:
  proxy_batch_write_at: 60
  database_connection_pool_limit: 10
  allow_requests_on_db_unavailable: True

environment_variables:
  PHOENIX_API_KEY: os.environ/PHOENIX_AP_KEY
  PHOENIX_COLLECTOR_ENDPOINT: os.environ/PHOENIX_COLLECTOR_ENDPOINT
  PHOENIX_PROJECT_NAME: os.environ/PHOENIX_PROJECT_NAME

